// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.24.0";

// src/lib/mcp/tools/list-companies.ts
import { createClient } from "npm:@supabase/supabase-js@^2.97.0";
import { defineTool } from "npm:@lovable.dev/mcp-js@0.24.0";
function db(ctx) {
  return createClient(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_companies_default = defineTool({
  name: "list_companies",
  title: "List companies (CNPJs)",
  description: "List all companies (CNPJs) the signed-in user belongs to, with id, org_id, name and CNPJ.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated())
      return { content: [{ type: "text", text: "N\xE3o autenticado" }], isError: true };
    const supabase = db(ctx);
    const { data: members, error: mErr } = await supabase.from("company_members").select("company_id, role").eq("user_id", ctx.getUserId());
    if (mErr) return { content: [{ type: "text", text: mErr.message }], isError: true };
    const ids = (members ?? []).map((m) => m.company_id);
    if (ids.length === 0)
      return {
        content: [{ type: "text", text: "Nenhuma empresa vinculada a este usu\xE1rio." }],
        structuredContent: { companies: [] }
      };
    const { data: companies, error: cErr } = await supabase.from("companies").select("id, org_id, name, cnpj").in("id", ids);
    if (cErr) return { content: [{ type: "text", text: cErr.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(companies, null, 2) }],
      structuredContent: { companies: companies ?? [] }
    };
  }
});

// src/lib/mcp/tools/list-transactions.ts
import { createClient as createClient2 } from "npm:@supabase/supabase-js@^2.97.0";
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z } from "npm:zod@^3.25.76";
function db2(ctx) {
  return createClient2(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_transactions_default = defineTool2({
  name: "list_transactions",
  title: "List company transactions",
  description: "List PJ (empresa) financial transactions for a given company_id. Optional date range (ISO YYYY-MM-DD) and limit (max 200). Requires the caller to be a member of the company.",
  inputSchema: {
    company_id: z.string().uuid().describe("Company UUID (see list_companies)."),
    from: z.string().optional().describe("Start date, inclusive, ISO YYYY-MM-DD."),
    to: z.string().optional().describe("End date, inclusive, ISO YYYY-MM-DD."),
    limit: z.number().int().positive().optional().describe("Max rows to return (default 50, cap 200).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ company_id, from, to, limit }, ctx) => {
    if (!ctx.isAuthenticated())
      return { content: [{ type: "text", text: "N\xE3o autenticado" }], isError: true };
    const capped = Math.min(Math.max(limit ?? 50, 1), 200);
    let q = db2(ctx).from("transactions").select(
      "id, date, type, description, amount, status, source, account_id, cost_center_id, is_intercompany"
    ).eq("company_id", company_id).order("date", { ascending: false }).limit(capped);
    if (from) q = q.gte("date", from);
    if (to) q = q.lte("date", to);
    const { data, error } = await q;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { transactions: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/create-transaction.ts
import { createClient as createClient3 } from "npm:@supabase/supabase-js@^2.97.0";
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z as z2 } from "npm:zod@^3.25.76";
function db3(ctx) {
  return createClient3(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var create_transaction_default = defineTool3({
  name: "create_transaction",
  title: "Create company transaction",
  description: "Register a new manual PJ (empresa) transaction. Type must be 'revenue' or 'expense'. Amount is BRL, always positive. Date is ISO YYYY-MM-DD. The entry is created as status='confirmed' and source='mcp', so it counts in the DRE exactly like a manual entry typed in the app.",
  inputSchema: {
    company_id: z2.string().uuid().describe("Company UUID (see list_companies)."),
    type: z2.enum(["revenue", "expense"]).describe("revenue = receita, expense = despesa."),
    amount: z2.number().positive().describe("Amount in BRL, positive."),
    date: z2.string().describe("Transaction date, ISO YYYY-MM-DD."),
    description: z2.string().min(1).describe("Human-readable description."),
    account_id: z2.string().uuid().optional().describe("Chart-of-accounts UUID (optional)."),
    bank_account_id: z2.string().uuid().optional().describe("Bank account UUID (optional)."),
    cost_center_id: z2.string().uuid().optional().describe("Cost center UUID (optional).")
  },
  annotations: { readOnlyHint: false, destructiveHint: false, openWorldHint: false },
  handler: async (input, ctx) => {
    if (!ctx.isAuthenticated())
      return { content: [{ type: "text", text: "N\xE3o autenticado" }], isError: true };
    const { data, error } = await db3(ctx).from("transactions").insert({
      company_id: input.company_id,
      // NOT NULL na tabela e exigido pela policy de INSERT (user_id = auth.uid()).
      user_id: ctx.getUserId(),
      type: input.type,
      amount: input.amount,
      date: input.date,
      description: input.description,
      account_id: input.account_id ?? null,
      bank_account_id: input.bank_account_id ?? null,
      cost_center_id: input.cost_center_id ?? null,
      // Mesma régua do lançamento manual da UI: só status='confirmed' entra no DRE.
      status: "confirmed",
      source: "mcp"
    }).select().single();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: `Transa\xE7\xE3o criada (id: ${data.id})` }],
      structuredContent: { transaction: data }
    };
  }
});

// src/lib/mcp/tools/list-receivables.ts
import { createClient as createClient4 } from "npm:@supabase/supabase-js@^2.97.0";
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z as z3 } from "npm:zod@^3.25.76";
function db4(ctx) {
  return createClient4(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_receivables_default = defineTool4({
  name: "list_receivables",
  title: "List accounts receivable",
  description: "List receivables (contas a receber) for a company. Optional status filter and limit (max 200).",
  inputSchema: {
    company_id: z3.string().uuid().describe("Company UUID."),
    status: z3.string().optional().describe("Optional status filter (e.g. 'pending', 'received')."),
    limit: z3.number().int().positive().optional().describe("Max rows (default 50, cap 200).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ company_id, status, limit }, ctx) => {
    if (!ctx.isAuthenticated())
      return { content: [{ type: "text", text: "N\xE3o autenticado" }], isError: true };
    const capped = Math.min(Math.max(limit ?? 50, 1), 200);
    let q = db4(ctx).from("receivables").select("*").eq("company_id", company_id).order("due_date", { ascending: true }).limit(capped);
    if (status) q = q.eq("status", status);
    const { data, error } = await q;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { receivables: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/list-bills-payable.ts
import { createClient as createClient5 } from "npm:@supabase/supabase-js@^2.97.0";
import { defineTool as defineTool5 } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z as z4 } from "npm:zod@^3.25.76";
function db5(ctx) {
  return createClient5(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_bills_payable_default = defineTool5({
  name: "list_bills_payable",
  title: "List accounts payable",
  description: "List bills payable (contas a pagar) for a company, ordered by due date (column 'vencimento'). Optional status filter and limit (max 200).",
  inputSchema: {
    company_id: z4.string().uuid().describe("Company UUID."),
    status: z4.string().optional().describe("Optional status filter (e.g. 'pending', 'paid')."),
    limit: z4.number().int().positive().optional().describe("Max rows (default 50, cap 200).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ company_id, status, limit }, ctx) => {
    if (!ctx.isAuthenticated())
      return { content: [{ type: "text", text: "N\xE3o autenticado" }], isError: true };
    const capped = Math.min(Math.max(limit ?? 50, 1), 200);
    let q = db5(ctx).from("bills_payable").select("*").eq("company_id", company_id).order("vencimento", { ascending: true }).limit(capped);
    if (status) q = q.eq("status", status);
    const { data, error } = await q;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { bills: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/cash-summary.ts
import { createClient as createClient6 } from "npm:@supabase/supabase-js@^2.97.0";
import { defineTool as defineTool6 } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z as z5 } from "npm:zod@^3.25.76";
function db6(ctx) {
  return createClient6(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var cash_summary_default = defineTool6({
  name: "cash_summary",
  title: "Cash summary (revenue vs expense)",
  description: "Summary of a company's revenue, expenses and net result in a date range. Dates ISO YYYY-MM-DD. Uses the same rule as the app's DRE: only confirmed entries, intercompany transfers excluded \u2014 so the numbers match what the user sees on screen.",
  inputSchema: {
    company_id: z5.string().uuid().describe("Company UUID."),
    from: z5.string().describe("Start date, inclusive."),
    to: z5.string().describe("End date, inclusive.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ company_id, from, to }, ctx) => {
    if (!ctx.isAuthenticated())
      return { content: [{ type: "text", text: "N\xE3o autenticado" }], isError: true };
    const { data, error } = await db6(ctx).from("transactions").select("type, amount").eq("company_id", company_id).eq("status", "confirmed").eq("is_intercompany", false).gte("date", from).lte("date", to);
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    const rows = data ?? [];
    let revenue = 0;
    let expense = 0;
    for (const r of rows) {
      const v = Number(r.amount) || 0;
      if (r.type === "revenue") revenue += v;
      else if (r.type === "expense") expense += v;
    }
    const net = revenue - expense;
    const fmt = (n) => n.toLocaleString("pt-BR", { style: "currency", currency: "BRL" });
    return {
      content: [
        {
          type: "text",
          text: `Per\xEDodo ${from} \u2192 ${to}
Receitas: ${fmt(revenue)}
Despesas: ${fmt(expense)}
Resultado l\xEDquido: ${fmt(net)}
(${rows.length} lan\xE7amentos)`
        }
      ],
      structuredContent: { revenue, expense, net, count: rows.length, from, to }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "ccrucecqmgfofbbwlpya";
var mcp_default = defineMcp({
  name: "financeai-mcp",
  title: "FinanceAI",
  version: "0.1.0",
  instructions: "Ferramentas do FinanceAI (ERP financeiro para empresas brasileiras). Use `list_companies` para descobrir os CNPJs vinculados ao usu\xE1rio, depois passe o `company_id` para as demais ferramentas. Valores em BRL, datas em ISO YYYY-MM-DD. Todas as chamadas respeitam a permiss\xE3o de membro da empresa (RLS).",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [
    list_companies_default,
    list_transactions_default,
    create_transaction_default,
    list_receivables_default,
    list_bills_payable_default,
    cash_summary_default
  ]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.24.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
