// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://canwvqgovjmejwiaxxfy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNhbnd2cWdvdmptZWp3aWF4eGZ5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODU4OTE5MjksImV4cCI6MjEwMTQ2NzkyOX0.bEAxQ_qZMGjaQbTarJyP18R-s_ewaUPRGMwrQbE1TzY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: typeof window !== 'undefined' ? localStorage : undefined,
    persistSession: true,
    autoRefreshToken: true,
  }
});